//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Book_To_Authors = new HashSet<Book_To_Authors>();
            this.Book_To_Readers = new HashSet<Book_To_Readers>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string PDF { get; set; }
        public int TotalCount { get; set; }
        public int BusyCount { get; set; }
        public string Description { get; set; }
        public Nullable<int> Genres_ID { get; set; }
        public string ISBN { get; set; }
        public byte Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_To_Authors> Book_To_Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_To_Readers> Book_To_Readers { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
