//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Net_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_To_Authors
    {
        public int id { get; set; }
        public Nullable<int> Book_ID { get; set; }
        public Nullable<int> Author_ID { get; set; }
        public byte Status { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
